Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false